<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "poloko"
 *
 * Auto generated by Extension Builder 2015-08-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TransitArt',
	'description' => 'TransitArt: Material UI Timetables KIT – easy timetables data visualization for your website or mobile app.',
	'category' => 'plugin',
	'author' => 'TransitArt Team',
	'author_email' => 'office@transitart.io',
        'author_company' => 'Inovatica',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.3-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);